_name_or_path:
    value: ilsp/Llama-Krikri-8B-Instruct
_wandb:
    value:
        cli_version: 0.23.1
        e:
            r9t2fuqd0suvygwzfy1rmef42w63l0yp:
                args:
                    - --exp
                    - "2"
                codePath: speechLM_utils/train.py
                codePathLocal: speechLM_utils/train.py
                cpu_count: 48
                cpu_count_logical: 96
                disk:
                    /:
                        total: "7459416539136"
                        used: "219332325376"
                email: chrissiargas@gmail.com
                executable: /home/jovyan/miniconda/envs/nemo2/bin/python
                host: greekasr5-0
                memory:
                    total: "1204529893376"
                os: Linux-5.10.234-225.895.amzn2.x86_64-x86_64-with-glibc2.39
                program: /home/jovyan/home/jovyan/greek-asr-master/speechLM_utils/train.py
                python: CPython 3.10.19
                root: /home/jovyan/home/jovyan/greek-asr-master
                startedAt: "2026-04-21T08:19:02.077732Z"
                writerId: r9t2fuqd0suvygwzfy1rmef42w63l0yp
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 98
                - 100
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 63
                - 71
                - 98
                - 100
            "3":
                - 2
                - 7
                - 13
                - 15
                - 16
                - 61
                - 66
            "4": 3.10.19
            "5": 0.23.1
            "6": 4.53.3
            "9":
                "1": transformers_trainer
            "10":
                - 20
            "12": 0.23.1
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
acoustic_lora:
    value: false
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
add_to_vocab:
    value: false
architectures:
    value:
        - LlamaForCausalLM
attention_bias:
    value: false
attention_dropout:
    value: 0
audio_forecasting:
    value: false
audio_weight:
    value: 0.5
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: false
bad_words_ids:
    value: null
batch_eval_metrics:
    value: false
begin_suppress_tokens:
    value: null
bf16:
    value: false
bf16_full_eval:
    value: false
blank_training:
    value: false
bos_token_id:
    value: 128000
causal_fusion:
    value: false
checkpoint_path:
    value: cache/checkpoints
chunk_size_feed_forward:
    value: 0
cross_attention_hidden_size:
    value: null
ctc:
    value: false
ctc_weight:
    value: 0.1
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 4
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: null
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: true
ddp_timeout:
    value: 1800
debug:
    value: []
decoder_start_token_id:
    value: null
deepspeed:
    value: null
disable_tqdm:
    value: false
diversity_penalty:
    value: 0
do_eval:
    value: true
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: true
downsample_K:
    value: 5
downsample_L:
    value: 5
downsamplers:
    value: injection_common
dropout:
    value: 0.2
duration_resolution:
    value: 0.1
early_stopping:
    value: false
early_stopping_patience:
    value: 15
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value:
        - 128001
        - 128008
        - 128009
eval_accumulation_steps:
    value: 2
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: 500
eval_strategy:
    value: steps
eval_use_gather_object:
    value: false
exponential_decay_length_penalty:
    value: null
finetuning_task:
    value: null
first_stage_epochs:
    value: 10
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: true
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
gated_cross_attention:
    value: false
generation_config:
    value:
        _from_model_config: false
        assistant_confidence_threshold: 0.4
        assistant_early_exit: null
        assistant_lookbehind: 10
        bad_words_ids: null
        begin_suppress_tokens: null
        bos_token_id: null
        cache_config: null
        cache_implementation: null
        constraints: null
        decoder_start_token_id: null
        disable_compile: false
        diversity_penalty: 0
        do_sample: false
        dola_layers: null
        early_stopping: false
        encoder_no_repeat_ngram_size: 0
        encoder_repetition_penalty: 1
        eos_token_id: null
        epsilon_cutoff: 0
        eta_cutoff: 0
        exponential_decay_length_penalty: null
        force_words_ids: null
        forced_bos_token_id: null
        forced_eos_token_id: null
        guidance_scale: null
        is_assistant: false
        length_penalty: 1
        low_memory: null
        max_length: 20
        max_matching_ngram_size: null
        max_new_tokens: 410
        max_time: null
        min_length: 0
        min_new_tokens: null
        min_p: null
        no_repeat_ngram_size: 0
        num_assistant_tokens: 20
        num_assistant_tokens_schedule: constant
        num_beam_groups: 1
        num_beams: 1
        num_return_sequences: 1
        output_attentions: false
        output_hidden_states: false
        output_logits: null
        output_scores: false
        pad_token_id: null
        penalty_alpha: null
        prefill_chunk_size: null
        prompt_lookup_num_tokens: null
        remove_invalid_values: false
        renormalize_logits: false
        repetition_penalty: 1
        return_dict_in_generate: false
        return_legacy_cache: null
        sequence_bias: null
        stop_strings: null
        suppress_tokens: null
        target_lookbehind: 10
        temperature: 1
        token_healing: false
        top_k: 50
        top_p: 1
        transformers_version: 4.53.3
        typical_p: 1
        use_cache: true
        watermarking_config: null
generation_max_length:
    value: 410
generation_num_beams:
    value: null
gradient_accumulation_steps:
    value: 4
gradient_checkpointing:
    value: true
gradient_checkpointing_kwargs:
    value:
        use_reentrant: false
greater_is_better:
    value: false
group_by_length:
    value: false
half_precision_backend:
    value: auto
has_decoder:
    value: false
head_dim:
    value: 128
hidden_act:
    value: silu
hidden_dim:
    value: 2048
hidden_size:
    value: 4096
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_revision:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: false
include_tokens_per_second:
    value: false
initializer_range:
    value: 0.02
injection_downsample:
    value: conv1d
injection_layers:
    value:
        - 5
        - 15
        - 25
input_downsample:
    value: reshape
interleave_temperature:
    value: 1.2
intermediate_size:
    value: 14336
is_decoder:
    value: false
is_encoder_decoder:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: null
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
learning_rate:
    value: 5e-05
length_column_name:
    value: length
length_penalty:
    value: 1
liger_kernel_config:
    value: null
linguistic_lora:
    value: true
load_best_model_at_end:
    value: true
local_rank:
    value: 0
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: /home/jovyan/cache/checkpoints/dual_fusion_checkpoints/greekasr5-0/whisper-large-v3_Llama-Krikri-8B-Instruct/LoRA_1_['common_voice', 'fleurs', 'hparl', 'tedx', 'logotypographia']@Apr21_08-18
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 10
logging_strategy:
    value: steps
lora_lr:
    value: 0.0001
lora_params:
    value:
        - q_proj
        - k_proj
        - v_proj
        - o_proj
lr_scheduler_type:
    value: linear
max_duration:
    value: 30
max_grad_norm:
    value: 1
max_length:
    value: 20
max_position_embeddings:
    value: 131072
max_steps:
    value: -1
metric_for_best_model:
    value: eval_wer
micro_data:
    value: false
micro_size:
    value: 800
min_length:
    value: 0
mlp_bias:
    value: false
model_type:
    value: llama
mp_parameters:
    value: ""
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
norm_mono:
    value: false
num_attention_heads:
    value: 32
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_hidden_layers:
    value: 32
num_key_value_heads:
    value: 8
num_return_sequences:
    value: 1
num_train_epochs:
    value: 60
optim:
    value: adamw_torch
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: /home/jovyan/cache/checkpoints/dual_fusion_checkpoints/greekasr5-0/whisper-large-v3_Llama-Krikri-8B-Instruct/LoRA_1_['common_voice', 'fleurs', 'hparl', 'tedx', 'logotypographia']@Apr21_08-18
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: false
pad_token_id:
    value: null
past_index:
    value: -1
per_device_eval_batch_size:
    value: 4
per_device_train_batch_size:
    value: 2
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
predict_duration:
    value: false
predict_with_generate:
    value: true
prediction_loss_only:
    value: false
prefix:
    value: null
pretraining_tp:
    value: 1
problem_type:
    value: null
proj_lr:
    value: 0.0001
project:
    value: false
prompt_instruction:
    value: " \nTranscribe the previous audio content into Greek text precisely."
prompt_persona:
    value: none
push_to_hub:
    value: false
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
pyramid_layers:
    value: false
quantization_config:
    value:
        _load_in_4bit: true
        _load_in_8bit: false
        bnb_4bit_compute_dtype: float32
        bnb_4bit_quant_storage: uint8
        bnb_4bit_quant_type: nf4
        bnb_4bit_use_double_quant: true
        llm_int8_enable_fp32_cpu_offload: false
        llm_int8_has_fp16_weight: false
        llm_int8_skip_modules: null
        llm_int8_threshold: 6
        load_in_4bit: true
        load_in_8bit: false
        quant_method: BITS_AND_BYTES
randomize:
    value: true
ray_scope:
    value: last
remove_invalid_values:
    value: false
remove_unused_columns:
    value: false
repetition_penalty:
    value: 1
report_to:
    value:
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
rms_norm_eps:
    value: 1e-05
rope_scaling:
    value:
        factor: 8
        high_freq_factor: 4
        low_freq_factor: 1
        original_max_position_embeddings: 8192
        rope_type: llama3
rope_theta:
    value: 500000
run_name:
    value: /home/jovyan/cache/checkpoints/dual_fusion_checkpoints/greekasr5-0/whisper-large-v3_Llama-Krikri-8B-Instruct/LoRA_1_['common_voice', 'fleurs', 'hparl', 'tedx', 'logotypographia']@Apr21_08-18
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: true
save_steps:
    value: 500
save_strategy:
    value: steps
save_total_limit:
    value: 3
second_stage_epochs:
    value: 40
seed:
    value: 42
sep_token_id:
    value: null
skip_memory_metrics:
    value: true
sortish_sampler:
    value: false
spec_augment:
    value: true
static_projector:
    value: true
suppress_tokens:
    value: null
task_specific_params:
    value: null
temperature:
    value: 1
text_dropout:
    value: false
tf_legacy_loss:
    value: false
tf32:
    value: null
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: false
tokenizer_class:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_dtype:
    value: float32
torch_empty_cache_steps:
    value: null
torchdynamo:
    value: null
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
training_args:
    value:
        dataloader_num_workers: 4
        dataloader_pin_memory: true
        ddp_find_unused_parameters: true
        do_train: true
        eval_accumulation_steps: 2
        eval_steps: 500
        eval_strategy: steps
        fp16: true
        generation_config: |
            GenerationConfig {
              "max_new_tokens": 410
            }
        generation_max_length: 410
        gradient_accumulation_steps: 4
        gradient_checkpointing: true
        gradient_checkpointing_kwargs:
            use_reentrant: false
        greater_is_better: false
        group_by_length: false
        load_best_model_at_end: true
        logging_dir: /home/jovyan/cache/checkpoints/dual_fusion_checkpoints/greekasr5-0/whisper-large-v3_Llama-Krikri-8B-Instruct/LoRA_1_['common_voice', 'fleurs', 'hparl', 'tedx', 'logotypographia']@Apr21_08-18
        logging_steps: 10
        lr_scheduler_type: linear
        metric_for_best_model: eval_wer
        num_train_epochs: 60
        optim: adamw_torch
        output_dir: /home/jovyan/cache/checkpoints/dual_fusion_checkpoints/greekasr5-0/whisper-large-v3_Llama-Krikri-8B-Instruct/LoRA_1_['common_voice', 'fleurs', 'hparl', 'tedx', 'logotypographia']@Apr21_08-18
        per_device_eval_batch_size: 4
        per_device_train_batch_size: 2
        predict_with_generate: true
        remove_unused_columns: false
        report_to:
            - wandb
        save_steps: 500
        save_strategy: steps
        save_total_limit: 3
        warmup_steps: 400
transformers_version:
    value: 4.53.3
two_stage:
    value: false
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cache:
    value: false
use_cpu:
    value: false
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
use_liger_kernel:
    value: false
use_mps_device:
    value: false
vocab_size:
    value: 149248
warmup_ratio:
    value: 0
warmup_steps:
    value: 400
weight_decay:
    value: 0
